- name: Check if Sublime is installed
  stat:
    path: "{{ HOME_DIR }}/Sublime/sublime_text"
  register: sublime

- name: Add Sublime GPG key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Checking APT works with https
  apt:
    name: apt-transport-https
  when: sublime.stat.exists == False

- name: Add Sublime Repo
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present
    update_cache: yes

- name: Installing Sublime
  apt:
    state: present
    name: sublime-text
    update_cache: yes
